export const API_TIMEOUT = 0;

export const NO_VERIFICATION_NEEDED = 'NO_VERIFICATION_NEEDED';

export const NO_VERIFICATION_CONFIG = { params: NO_VERIFICATION_NEEDED };

export { default as AccountsService } from './AccountsService';
export { default as AttendanceLogsService } from './AttendanceLogsService';
export { default as AttendanceSchedulesService } from './AttendanceSchedulesService';
export { default as AuthService } from './AuthService';
export { default as BackOrdersService } from './BackOrdersService';
export { default as BalanceAdjustmentLogService } from './BalanceAdjustmentLogService';
export { default as BirReportsService } from './BirReportsService';
export { default as BranchAssignmentsService } from './BranchAssignmentsService';
export { default as BranchesDayService } from './BranchesDayService';
export { default as BranchesDaysService } from './BranchesDaysService';
export { default as BranchesService } from './BranchesService';
export { default as BranchMachinesService } from './BranchMachinesService';
export { default as BranchProductsService } from './BranchProductsService';
export { default as CashBreakdownsService } from './CashBreakdownsService';
export { default as CashieringAssignmentsService } from './CashieringAssignmentsService';
export { default as CashieringSessionsService } from './CashieringSessionsService';
export { default as CollectionReceiptsService } from './CollectionReceiptsService';
export { default as ConnectivityLogsService } from './ConnectivityLogsService';
export { default as CreditRegistrationsService } from './CreditRegistrationsService';
export { default as DataService } from './DataService';
export { default as DiscountOptionsService } from './DiscountOptionsService';
export { default as InvoiceService } from './InvoiceService';
export { default as LogsService } from './LogsService';
export { default as NetworkService } from './NetworkService';
export { default as OrderOfPaymentsService } from './OrderOfPaymentsService';
export { default as PointSystemTagsService } from './PointSystemTagsService';
export { default as PointTransactionsService } from './PointTransactionsService';
export { default as PriceMarkdownsService } from './PriceMarkdownsService';
export { default as ProductCategoriesService } from './ProductCategoriesService';
export { default as ProductChecksService } from './ProductChecksService';
export { default as ProductsService } from './ProductsService';
export { default as ReceivingVouchersService } from './ReceivingVouchersService';
export { default as RequisitionSlipsService } from './RequisitionSlipsService';
export { default as SalesTrackerService } from './SalesTrackerService';
export { default as SessionsService } from './SessionsService';
export { default as SiteSettingsService } from './SiteSettingsService';
export { default as SupplierRegistrationsService } from './SupplierRegistrationsService';
export { default as TransactionProductsService } from './TransactionProductsService';
export { default as TransactionsService } from './TransactionsService';
export { default as UserLogsService } from './UserLogsService';
export { default as UsersService } from './UsersService';
export { default as XReadReportsService } from './XReadReportsService';
export { default as ZReadReportsService } from './ZReadReportsService';
